# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IRC-SPHERE
email: sphere-admin@bristol.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  SPHERE - a Sensor Platform for HEalthcare in a Residential Environment
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://irc-sphere.github.io" # the base hostname & protocol for your site
twitter_username: irc_sphere
github_username:  IRC-SPHERE

# Build settings
markdown: kramdown
